# Email related properties

police.mail.sending.mode=LIVE
#police.mail.sending.mode=STAGING_ALTERNATIVE


# For Staging And Production
#police.mail.host=192.168.2.6
#police.mail.port=465
police.mail.host=172.20.203.05
police.mail.port=25
#police.mail.sender=noreply@lankagate.gov.lk
police.mail.sender=noreply_police@lgc2.gov.lk
police.mail.authenticate=TRUE
#police.mail.authenticateUserId=noreply@lankagate.gov.lk
#police.mail.authenticatePwd=dfse#12$
police.mail.authenticateUserId=noreply_police@lgc2.gov.lk
police.mail.authenticatePwd=noreply@#7890
police.mail.ssLFactory=javax.net.ssl.SSLSocketFactory


police.mail.alternative.username=icta.eservices.analytics@gmail.com
police.mail.alternative.password=1qaz2wsx1qaz2wsx
police.mail.alternative.port=465
police.mail.alternative.host=smtp.gmail.com
												
													