#Configuration for save service provider user account's in Common User Database
serviceprovider.services=9,New Application,1,1|10,Re-apply COO,1,1|11,Request Copies,1,1

police.nic.passport.file.upload.location=/volume1/Deployments/Police/uploadFiles/
police.nic.passport.file.upload.location.finder=/volume1/Deployments/Police/uploadFiles
police.report.file.location=/home/Deployments/Police/Report_Files/