# Email related properties

police.mail.sending.mode=LIVE
#police.mail.sending.mode=STAGING_ALTERNATIVE


# For Staging And Production
#police.mail.host=192.168.2.6
#police.mail.port=587
#police.mail.host=103.11.35.12
#police.mail.port=465
police.mail.host=10.250.6.4
police.mail.port=465
#police.mail.sender=noreply@lankagate.gov.lk
police.mail.sender=noreply-police@lankagate.gov.lk
police.mail.authenticate=TRUE
#police.mail.authenticateUserId=noreply@lankagate.gov.lk
#police.mail.authenticatePwd=dfse#12$
police.mail.authenticateUserId=noreply-police@lankagate.gov.lk
police.mail.authenticatePwd=N0R#$up%p!*859
police.mail.ssLFactory=javax.net.ssl.SSLSocketFactory


police.mail.alternative.username=icta.eservices.analytics@gmail.com
police.mail.alternative.password=1qaz2wsx1qaz2wsx
police.mail.alternative.port=465
police.mail.alternative.host=smtp.gmail.com

#Email scheduler cron
#Scheduler fires @ 8.00 PM Everyday
#mail.cron.expression=0 0 20 ? * *
mail.cron.expression=0 0 16 ? * *
#mail.cron.expression=0 0/5 * * * ? 
