rest.application.url=https://eservices.police.lk/SLPRestApplication/
#rest.application.url=http://testdwc.lankagate.gov.lk/SLPRestApplication/
#rest.application.url=http://localhost:8080/SLPRestApplication/

#for production
police.nic.passport.file.upload.location=/volume1/Deployments/Police/uploadFiles/
police.nic.passport.file.upload.location.finder=/volume1/Deployments/Police/uploadFiles

#for staging
#police.nic.passport.file.upload.location=/home/Deployments/Police/uploadFiles/
#police.nic.passport.file.upload.location.finder=/home/Deployments/Police/uploadFiles

police.report.file.location=/home/Deployments/Police/Report_Files/
#maximum file upload size in kb
police.maximum.upload.file.size.limit=250000