#Bulk sms url
sms.end.point.url=http://lankagate.gov.lk:9080/services/GovSMSMTHandlerProxy.GovSMSMTHandlerProxyHttpSoap12Endpoint
#bulk.sms.end.point.url=http://lixexternal.lankagate.gov.lk:9080/services/GovSMSMTHandlerProxy.GovSMSMTHandlerProxyHttpSoap12Endpoint

#Bulk sms scheduler cron
#Scheduler fires @ 8.00 PM Everyday
#sms.cron.expression=0 0 20 ? * *
sms.cron.expression=0 0 16 ? * *
#sms.cron.expression=0 0/5 * * * ? 

#SMS log file path
sms.log.file.path.without.file.name=D:/