# Email related properties

police.mail.sending.mode=LIVE
#police.mail.sending.mode=STAGING_ALTERNATIVE


# For Staging And Production
#police.mail.host=192.168.2.6
#police.mail.port=587
#police.mail.host=103.11.35.12
#police.mail.port=465
police.mail.host=10.250.6.4
police.mail.port=465
#police.mail.sender=noreply@lankagate.gov.lk
police.mail.sender=noreply-police@lankagate.gov.lk
police.mail.authenticate=TRUE
#police.mail.authenticateUserId=noreply@lankagate.gov.lk
#police.mail.authenticatePwd=dfse#12$
police.mail.authenticateUserId=noreply-police@lankagate.gov.lk
police.mail.authenticatePwd=N0R#$up%p!*859
police.mail.ssLFactory=javax.net.ssl.SSLSocketFactory


police.mail.alternative.username=icta.eservices.analytics@gmail.com
police.mail.alternative.password=1qaz2wsx1qaz2wsx
police.mail.alternative.port=587
police.mail.alternative.host=smtp.gmail.com

#Email scheduler cron
#Scheduler fires @ 8.00 PM Everyday
#mail.cron.expression=0 0 20 ? * *
mail.cron.expression=0 0 16 ? * *
#mail.cron.expression=0 0/5 * * * ? 


police.mail.content.update.in.police.area=<p>Dear {0},</p>\
													<p>The police area that you provided: ''{1}'' for the address: ''{2}'' \
													has been corrected as: ''{3}'' for your application with reference no: {4}. \
													Please be informed that this will cause a delay in processing your application.</p>\
													<p>The Police Headquarters</p>
													
											 
police.mail.content.incorrect.address.period.of.stay=<p>Dear {0},</p>\
											<p>You have incorrectly stated your address/period as ''{1}'' for your application with reference no. {2}. \
											You are required to be present at the police Headquarters on <insert date and time> to \
											make the corrections to your application. Please be informed that this will cause a delay \
											in processing your application</p>.<p>The Police Headquarters</p>

police.mail.content.update.in.nic.name=<p>Date: {0}</p>\
									<p>My Number :{1} </p> \
									<p>{2}</p> \
									<p>Dear Sir/Madam,</p> \
									<p><u><b>With regard to correcting the name that appears on the National Identity Card bearing number {3}</b></u></p> \
									<p>The name that appears on your application does not match with the one that appears on your National Identity Card.</p> \
									<p>You are hereby informed to correct your name by bringing the originals and the photocopies of the following documents and by producing them to the Legal Division, Department for Registration of Persons at C45, Keppetipola Mawatha, Colombo 05. </p> \
									<ol><li>National Identity Card (Original)</li><li>Birth Certificate (Original) </li><li>Marriage Certificate (Original), if the name was altered after marriage </li><li>This letter sent to you by the Clearance Branch</li></ol> \
									<p>I wish to inform you that we are unable to issue a clearance  certificate until you resolve this discrepancy with regard to your name by producing the above mentioned documents to the Legal Division, Department for Registration of Persons .</p> \
									<p>Officer in Charge <br />Clearance Branch</p>
													
