# Mode should be either "LIVE" or "UT"
mode=LIVE

# If mode is "UT" following attributes should be set
commonUserURL=jdbc:mysql://localhost:3306/common_user
commonUserDriverClass=com.mysql.jdbc.Driver
commonUserUserName=common_user
commonUserPassword=common_user
