# Email related properties
########################## These are for production  #######################################
#commonuser.mail.host=192.168.2.6
#commonuser.mail.port=587
#commonuser.mail.host=103.11.35.12
#commonuser.mail.port=465
commonuser.mail.host=10.250.6.4
commonuser.mail.port=465
#commonuser.mail.sender=noreply@lankagate.gov.lk
commonuser.mail.sender=noreply-police@lankagate.gov.lk
commonuser.mail.authenticate=TRUE
#commonuser.mail.authenticateUserId=noreply@lankagate.gov.lk
#commonuser.mail.authenticatePwd=dfse#12$
commonuser.mail.authenticateUserId=noreply-police@lankagate.gov.lk
commonuser.mail.authenticatePwd=N0R#$up%p!*859
commonuser.mail.ssLFactory=javax.net.ssl.SSLSocketFactory
commonuser.mail.newPassword.subject=ICTA SLP eService - Your New Password
commonuser.mail.newPassword.content=Your username and new password for ICTA SLP eService is<br /><br /> Username \: {0} <br /><br /> Password \: {1} <br />

commonuser.mail.newPassword.title=ICTA SLP eService - Reset Password

commonuser.mail.sending.mode=LIVE
#commonuser.mail.sending.mode=STAGING_ALTERNATIVE

commonuser.mail.alternative.username=icta.eservices.analytics@gmail.com
commonuser.mail.alternative.password=1qaz2wsx!@#
commonuser.mail.alternative.port=587
commonuser.mail.alternative.host=smtp.gmail.com
